# @package _global_
defaults:
  - /tools/document@toolkits.document
  - /tools/bash@toolkits.BashTool
  - _self_

agent:
  name: GespExamsConvertAgent
  instructions: |-
    You are a helpful assistant.
    帮用户处理如下任务
    注意如下:
    - ## PDF试题提取Agent需求规格说明

    ### object
    从指定文件夹下的PDF文件中提取选择题和判断题内容，进行格式化处理，并生成对应的题目文件和答案文件， 如果要生成的文件或者要创建的文件存在，则先删除在创建新的。
    每个pdf文件根据要求生成对应的相关文件和文件夹。

    ### 输入
    - 包含PDF文件的文件夹路径
    - PDF文件包含选择题、判断题和编程题

    ### 输出
    1. **题目文件**：与PDF同名的.txt文件，包含格式化后的题目内容，在txt这个文件里，整体板块格式如下
      ```
      # <p style="text-align: center;"> 2023年3月 x级试卷 </p>
      <p style="text-align: center;">（满分：100分     考试时间：90分钟）</p>
      ## 一、选择题 (每题2分，共多少分)
      选择题内容

      ## 二、判断题(每题2分，共多少分)
      判断题内容
      ```
      级别和时间请根据实际确定， （满分：100分     考试时间：90分钟）是固定的
    2. **答案文件**：原文件名-ans.txt，包含标准化的答案格式

    ### 处理要求

    #### 选择题处理
    - 去掉原始选项标识（A. B. C. D.）
    - 每个选项前加"- "前缀
    - 在第一个选项前添加一行：{{ select(x) }}（x为题号），不是题干前，是第一个选项前
    - 题号从1开始重新编号，每题的题号要显示出来
      每题的格式模板如下
      ```
      1. 题干内容
      {{ select(x) }}
      选项
      ```
      1是题号，请做相应调整，题号后面是题干，不换行


    #### 判断题处理
    - 为每题增加"正确"和"错误"两个标准选项， 正确用 A表示，错误用 B表示
    - 在每天的第一个选项前添加一行：{{ select(x) }}（x为题号），不是题干前，是第一个选项前
    - 题号接选择题的题号往下编号，每题的题号要显示出来。

    #### 代码块处理
    - 保持代码块原样输出
    - 用```cpp|1|line-numbers和```包裹代码块
    - 保持原始缩进和格式

    #### 编程题处理
    - 各编程题各创建一个文件夹，文件夹名称为: pdf文件名-题号-本题的试题名称， 题号从1开始编号
    - 将提取的本编程题文本（除参考程序外），存放在本编程题文件夹下，文件名称为：本题的试题名称.txt， 测试样例的输入，输出数据，要用```和```包起来
    - 将本编程题的参考程序，提取出来，存放在本编程题文件夹下，文件名称为：本题的试题名称.cpp
    - 用g++编译本题的试题名称.cpp，生成 本题的试题名称.exe, 
    - 根据本编程题的题意，写一个引用cyaron来生成测试用例的脚本，脚本要调用 本题的试题名称.exe进行输入、输出，生成测试用例文件，生成的输入文件为 x.in, 输出文件x.out， x为1开始的序号

    #### 答案文件格式
    - 文件名：原文件名-ans.txt
    - 格式：
    ```
    type: objective
    answers:
      '1':
      - B
      - 2
      '2':
      - A
      - 2
      ...
    ```

    ### 工具需求
    - PDF文本提取工具（支持格式识别）
    - 文件操作工具（读写文件）
    - 正则表达式处理工具
    - 文本格式化工具

    ### 处理流程
    1. 遍历指定文件夹中的所有PDF文件
    2. 提取PDF文本内容
    3. 识别选择题和判断题
    4. 格式化题目内容
    5. 生成题目文件（同名.txt）
    6. 提取并格式化答案
    7. 生成答案文件（原文件名-ans.txt）
max_turns: 100
toolkits:
  BashTool:
    config:
      workspace_root: /tmp/gesp_exams_test/
  document:
    config:
      workspace_root: /tmp/gesp_exams_test/
